### ISSUE TITLE
ST3 doeas not higlight ini files automatically

### ISSUE THREAD

**Issue by rbaumi** [clintberry/sublime-text-2-ini#22]
As default .ini files are still opening as **Plain Text**. I have to manually select INI and then the content is highlighted correctly. After file is closed and reopened it's again displayed as Plain Text. 

In the [package repository](https://packagecontrol.io/packages/INI) it has a flag ST2/ST3 so I guess it should work with ST3, right?

**Comment by ChrisCummins** [comment]
I don't think that's an error with the package. Does 'View > Syntax > Open all with current extension as... > INI' not work?

**Comment by rbaumi** [comment]
Thanks @ChrisCummins !! After doing what you wrote it works like a charm! It opens that as ini file all time now! 

I suggest you add a note to the README file about this. I have tested it across latest release of ST3.
